import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/presentation/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/store/**/*.{js,ts,jsx,tsx}',
    './src/data/**/*.{js,ts}',
    './src/domain/**/*.{js,ts}',
  ],
  theme: {
    extend: {
      screens: { 'xs': '390px', 'sm': '640px' },
      keyframes: {
        verseFlash: {
          '0%':   { backgroundColor: 'transparent' },
          '20%':  { backgroundColor: '#fde68a' },
          '50%':  { backgroundColor: '#fde68a' },
          '100%': { backgroundColor: 'transparent' },
        },
      },
      animation: {
        'verse-flash': 'verseFlash 0.7s ease-in-out 3',
      },
      fontFamily: {
        sans:  ['var(--font-sans)', 'system-ui', 'sans-serif'],
        serif: ['var(--font-serif)', 'Georgia', 'serif'],
        // ── 한글 폰트 30개 ──────────────────────────
        'noto-sans-kr':             ['var(--font-noto-sans-kr)', 'sans-serif'],
        'noto-serif-kr':            ['var(--font-noto-serif-kr)', 'serif'],
        'gothic-a1':                ['var(--font-gothic-a1)', 'sans-serif'],
        'nanum-gothic':             ['var(--font-nanum-gothic)', 'sans-serif'],
        'nanum-myeongjo':           ['var(--font-nanum-myeongjo)', 'serif'],
        'nanum-gothic-coding':      ['var(--font-nanum-gothic-coding)', 'monospace'],
        'black-han-sans':           ['var(--font-black-han-sans)', 'sans-serif'],
        'do-hyeon':                 ['var(--font-do-hyeon)', 'sans-serif'],
        'jua':                      ['var(--font-jua)', 'sans-serif'],
        'sunflower':                ['var(--font-sunflower)', 'sans-serif'],
        'gaegu':                    ['var(--font-gaegu)', 'cursive'],
        'gamja-flower':             ['var(--font-gamja-flower)', 'cursive'],
        'hi-melody':                ['var(--font-hi-melody)', 'cursive'],
        'kirang-haerang':           ['var(--font-kirang-haerang)', 'cursive'],
        'yeon-sung':                ['var(--font-yeon-sung)', 'cursive'],
        'poor-story':               ['var(--font-poor-story)', 'cursive'],
        'east-sea-dokdo':           ['var(--font-east-sea-dokdo)', 'cursive'],
        'cute-font':                ['var(--font-cute-font)', 'cursive'],
        'song-myung':               ['var(--font-song-myung)', 'serif'],
        'nanum-pen-script':         ['var(--font-nanum-pen-script)', 'cursive'],
        'gugi':                     ['var(--font-gugi)', 'sans-serif'],
        'gowun-dodum':              ['var(--font-gowun-dodum)', 'sans-serif'],
        'gowun-batang':             ['var(--font-gowun-batang)', 'serif'],
        'orbit':                    ['var(--font-orbit)', 'sans-serif'],
        'hahmlet':                  ['var(--font-hahmlet)', 'serif'],
        'ibm-plex-sans-kr':         ['var(--font-ibm-plex-sans-kr)', 'sans-serif'],
        'single-day':               ['var(--font-single-day)', 'cursive'],
        'dokdo':                    ['var(--font-dokdo)', 'cursive'],
        'nanum-brush-script':       ['var(--font-nanum-brush-script)', 'cursive'],
        'black-and-white-picture':  ['var(--font-black-and-white-picture)', 'cursive'],
        // ── 영문 폰트 30개 ──────────────────────────
        'lora':               ['var(--font-lora)', 'serif'],
        'merriweather':       ['var(--font-merriweather)', 'serif'],
        'eb-garamond':        ['var(--font-eb-garamond)', 'serif'],
        'playfair-display':   ['var(--font-playfair-display)', 'serif'],
        'crimson-text':       ['var(--font-crimson-text)', 'serif'],
        'cormorant-garamond': ['var(--font-cormorant-garamond)', 'serif'],
        'libre-baskerville':  ['var(--font-libre-baskerville)', 'serif'],
        'spectral':           ['var(--font-spectral)', 'serif'],
        'pt-serif':           ['var(--font-pt-serif)', 'serif'],
        'alegreya':           ['var(--font-alegreya)', 'serif'],
        'josefin-sans':       ['var(--font-josefin-sans)', 'sans-serif'],
        'raleway':            ['var(--font-raleway)', 'sans-serif'],
        'nunito':             ['var(--font-nunito)', 'sans-serif'],
        'open-sans':          ['var(--font-open-sans)', 'sans-serif'],
        'poppins':            ['var(--font-poppins)', 'sans-serif'],
        'work-sans':          ['var(--font-work-sans)', 'sans-serif'],
        'dm-sans':            ['var(--font-dm-sans)', 'sans-serif'],
        'source-serif-4':     ['var(--font-source-serif-4)', 'serif'],
        'frank-ruhl-libre':   ['var(--font-frank-ruhl-libre)', 'serif'],
        'inter':              ['var(--font-inter)', 'sans-serif'],
        'roboto':             ['var(--font-roboto)', 'sans-serif'],
        'montserrat':         ['var(--font-montserrat)', 'sans-serif'],
        'ubuntu':             ['var(--font-ubuntu)', 'sans-serif'],
        'oswald':             ['var(--font-oswald)', 'sans-serif'],
        'lato':               ['var(--font-lato)', 'sans-serif'],
        'source-code-pro':    ['var(--font-source-code-pro)', 'monospace'],
        'roboto-slab':        ['var(--font-roboto-slab)', 'serif'],
        'bitter':             ['var(--font-bitter)', 'serif'],
        'arvo':               ['var(--font-arvo)', 'serif'],
        'vollkorn':           ['var(--font-vollkorn)', 'serif'],
      },
    },
  },
  plugins: [],
}

export default config
